/* Content hashes for the heavy files, generated by tools/hashes.mjs — do not hand-edit.
   [hash, gzipped bytes]. The hash is the cache key: see the tool for why. */
const ASSET_HASH = {
  "audio-grammar":["1735ba6f35",15239],
  "audio-kana":["4ccb84edfa",628534],
  "audio-konbini":["eab985c187",251858],
  "audio-place-asking":["4dcff546b5",55612],
  "audio-place-cafe":["9014cd0d7d",10450],
  "audio-place-casual":["26924984d9",32226],
  "audio-place-compliments":["756b429683",42544],
  "audio-place-diner":["d9667e37a2",58476],
  "audio-place-directions":["4ef591386e",76402],
  "audio-place-festival":["487f5d7508",50165],
  "audio-place-receipt":["813273d871",31634],
  "audio-place-road":["14c8029534",34649],
  "audio-place-sento":["a97ac45b0c",25625],
  "audio-place-shop":["61d87dcecb",66007],
  "audio-place-signs":["9c55ab60e7",65207],
  "audio-place-station":["02056462d3",378399],
  "audio-place-sushi":["f5a400766f",115648],
  "audio-s10":["745372ca20",232178],
  "audio-s2":["e5e1947d74",83947],
  "audio-s3":["3e63f626db",115136],
  "audio-s4":["0f22f90f13",146178],
  "audio-s5":["96b53d751e",256156],
  "audio-s6":["5c4d0e1709",315368],
  "audio-s7":["a7ebc70e6f",408328],
  "audio-s8":["308b038c09",365612],
  "audio-s9":["be0f49431b",408849],
  "strokes":["e1a2aa900d",187975]
};
const assetUrl = name => `js/${name}.js?h=${ASSET_HASH[name] ? ASSET_HASH[name][0] : APP_VERSION}`;
