/* Build js/strokes.js: stroke outlines and median lines for every single-
   glyph kana the app teaches, from AnimCJK's graphicsJaKana.txt.

   Source:  https://github.com/parsimonhi/animCJK (graphicsJaKana.txt)
   Licence: Arphic Public License — see licenses/animCJK/. The format is
            Make Me a Hanzi's: a 1024 box, y pointing up, baseline at 900.

     node tools/fetch-strokes.mjs            uses the cached copy if there is one
     node tools/fetch-strokes.mjs --refresh  downloads it again */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { join } from 'path';

const URL_SRC = 'https://raw.githubusercontent.com/parsimonhi/animCJK/master/graphicsJaKana.txt';
const root = fileURLToPath(new URL('../', import.meta.url));
const cacheDir = join(root, 'tools/.cache');
const cache = join(cacheDir, 'graphicsJaKana.txt');

export async function source(refresh = false) {
  if (refresh || !existsSync(cache)) {
    const r = await fetch(URL_SRC);
    if (!r.ok) throw new Error(`download failed: ${r.status}`);
    mkdirSync(cacheDir, { recursive: true });
    writeFileSync(cache, await r.text());
  }
  const out = {};
  readFileSync(cache, 'utf8').trim().split('\n').forEach(l => { const j = JSON.parse(l); out[j.character] = j; });
  return out;
}

/* Only single characters get writing drills: きゃ is two glyphs you already
   write, and ー is a line. */
export function wanted() {
  const { KANA } = new Function(readFileSync(join(root, 'js/data/kana.js'), 'utf8') + '\nreturn {KANA};')();
  return KANA.filter(e => [...e.k].length === 1 && e.k !== 'ー').map(e => e.k);
}

/* AnimCJK cuts a stroke that loops back over itself (あ's last stroke, the
   whole of の) into overlapping pieces, so it can animate them. A piece is
   recognisable by ending exactly where the stroke before it ends — the first
   piece already follows the whole path. For writing, a stroke is what the
   pen does without lifting, so the pieces are merged back: the first piece's
   median, and every piece's outline (the stroke animation clips to their
   union). Without this, あ counts as 4 strokes and ぬ as 4 — both wrong, and
   the marking requires the count to be exact.

   Output: { s: [[outline, …], …], m: [median, …] } — one entry per real stroke. */
export function mergePieces({ strokes, medians }) {
  const s = [], m = [];
  medians.forEach((med, i) => {
    const end = med[med.length - 1];
    const prev = m[m.length - 1];
    if (prev && prev[prev.length - 1][0] === end[0] && prev[prev.length - 1][1] === end[1]) {
      s[s.length - 1].push(strokes[i]);
    } else {
      s.push([strokes[i]]);
      m.push(med);
    }
  });
  return { s, m };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const src = await source(process.argv.includes('--refresh'));
  const data = {}, missing = [];
  wanted().forEach(c => {
    if (!src[c]) { missing.push(c); return; }
    data[c] = mergePieces(src[c]);
  });
  const out = `/* Stroke data for kana, generated by tools/fetch-strokes.mjs — do not hand-edit.
   From AnimCJK (https://github.com/parsimonhi/animCJK), Arphic Public License:
   see licenses/animCJK/. 1024 box, y up, baseline 900. Per kana: s = outlines
   for each stroke (a looped stroke has several), m = each stroke's median. */
window.NQ_STROKES = ${JSON.stringify(data)};
`;
  writeFileSync(join(root, 'js/strokes.js'), out);
  console.log(`${Object.keys(data).length} kana → js/strokes.js (${(out.length / 1024).toFixed(0)} KB)`);
  if (missing.length) console.log(`no strokes for: ${missing.join(' ')}`);
}
