/* Stamp the heavy, lazily loaded files with a hash of their own contents.

   Everything else in js/ is stamped ?v=<version> (see tools/version.mjs), and
   that's right for code: it changes on most pushes. The audio bundles and the
   stroke data are 90% of the bytes and almost never change, yet a version
   bump made every phone fetch all of them again. So they carry ?h=<hash>
   instead, and the URL only moves when the file does.

   Writes js/assets.js, which index.html loads before sound.js:
     ASSET_HASH  { "audio-s7": [hash, bytes over the wire], … }
     assetUrl(name)  the URL to fetch it from
   The byte count is the gzipped size, which is what GitHub Pages sends — it's
   what Settings → Offline shows as still to download.

   Run by version.mjs, make-audio.mjs and fetch-strokes.mjs; smoke.mjs fails
   if it's out of date. On its own:   node tools/hashes.mjs */

import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { createHash } from 'crypto';
import { gzipSync } from 'zlib';
import { fileURLToPath } from 'url';
import { join } from 'path';

const root = fileURLToPath(new URL('../', import.meta.url));
export const ASSETS_FILE = join(root, 'js/assets.js');

export function assetHashes() {
  const names = readdirSync(join(root, 'js')).filter(f => /^audio-.*\.js$/.test(f) || f === 'strokes.js').sort();
  return Object.fromEntries(names.map(f => {
    const body = readFileSync(join(root, 'js', f));
    return [f.replace(/\.js$/, ''), [createHash('sha1').update(body).digest('hex').slice(0, 10), gzipSync(body).length]];
  }));
}

export function assetsJs(hashes = assetHashes()) {
  return `/* Content hashes for the heavy files, generated by tools/hashes.mjs — do not hand-edit.
   [hash, gzipped bytes]. The hash is the cache key: see the tool for why. */
const ASSET_HASH = ${JSON.stringify(hashes, null, 0).replace(/\],"/g, '],\n  "').replace(/^\{/, '{\n  ').replace(/\}$/, '\n}')};
const assetUrl = name => \`js/\${name}.js?h=\${ASSET_HASH[name] ? ASSET_HASH[name][0] : APP_VERSION}\`;
`;
}

export function writeHashes() {
  const out = assetsJs();
  writeFileSync(ASSETS_FILE, out);
  return out;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeHashes();
  console.log(`hashed ${Object.keys(assetHashes()).length} files → js/assets.js`);
}
